services:
  row-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    volumes:
      - /home:/home
      - /data:/data
      - /home/gve/.streamlit:/root/.streamlit
      - /home/gve/Downloads/row_inspection_renew/models:/models

    env_file:
      - .env

    depends_on:
      - mysql

    extra_hosts:
      - "host.docker.internal:host-gateway"


  mysql:
    image: mysql:8.0
    container_name: row-mysql
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro


volumes:
  mysql_data: